...
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: webapp
spec:
  containers:
  - name: fleetman
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0
    ports:
    - containerPort: 80

--- 

apiVersion: v1
kind: Service
metadata:
  name: webapp-lb
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
    - port: 8080
      targetPort: 80

apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      nodePort: 32000