- name: Basic playbook
  hosts: all
  tasks:
    - name: Basic msg print task
      debug:
        msg: this is my first playbook
    - name: this my second task to run a command
      command: hostname 
      
